---
title: "Least squares as springs"
author: "Iñaki Úcar"
output:
  flexdashboard::flex_dashboard:
    orientation: row
    social: menu
    source_code: https://github.com/Enchufa2/ls-springs
    includes: 
      after_body: "busy.html"
runtime: shiny
---

```{r setup, include=FALSE}
library(plotly)
library(gganimate)
library(DT)
library(gifski)
options(warn=-1)

generate_data <- function(n, sigma, seed=NULL) {
  if (!is.null(seed)) set.seed(seed)
  
  X <- mvtnorm::rmvnorm(n, sigma=sigma)
  scale(X, scale=FALSE)
}

get_slope <- function(X, type=c("reg", "pca")) {
  if (match.arg(type) == "reg") {
    unname(coef(lm.fit(X[, 1, drop=FALSE], X[, 2])))
  } else {
    pca <- prcomp(X)
    unname(pca$rotation[2, 1]/pca$rotation[1, 1])
  }
}

get_projection <- function(X, pos, type=c("reg", "pca")) {
  w <- c(cos(pos[2] * pi/180), sin(pos[2] * pi/180))
  
  if (match.arg(type) == "reg") {
    z <- cbind(X[, 1], w[2] * X[, 1] / w[1])
    z[, 2] <- z[, 2] + pos[1]
  } else {
    z <- X %*% w %*% w
    z[, 1] <- z[, 1] - pos[1] * w[2]
    z[, 2] <- z[, 2] + pos[1] * w[1]
  }
  
  z
}

get_frame <- function(X, z, pos, t) {
  colnames(z) <- c("xend", "yend")
  names(pos) <- c("cm", "alpha")
  cbind(as.data.frame(X), z, t(pos), d=sqrt(rowSums((X - z)^2)), t=t)
}

generate_frames <- function(X, pos, type=c("reg", "pca"), loss=0.07,
                            inertia=40, tol=c(0.1, 1), max.iter=500)
{
  rest <- c(0, atan(get_slope(X, type)) * 180/pi)
  v <- c(0, 0)
  dfl <- list()
  X <- rbind(c(0, 0), X)
  
  for (t in seq_len(max.iter)) {
    z <- get_projection(X, pos, type)
    dfl[[t]] <- get_frame(X, z, pos, t)
    
    m <- c(-pos[1], sum((z %*% matrix(c(0, -1, 1, 0), ncol=2)) * (X - z)))
    v <- (v + m) * (1 - loss)
    pos <- pos + v / inertia
    
    if (all(abs(v) < tol) && all(abs(pos %% c(Inf, 360) - rest) < tol)) {
      pos <- c(rest[1], rest[2] + 360 * pos[2] %/% 360)
      z <- get_projection(X, pos, type)
      dfl[[t+1]] <- get_frame(X, z, pos, t+1)
      break
    }
  }
  
  do.call(rbind, dfl)
}

sigma <- reactiveVal(as.data.frame(matrix(c(1, 0.6, 0.6, 0.6), ncol=2)))
```

## Configuration {.sidebar data-width=300}

```{r}
span()
selectInput(
  "type", "Type:", 
  choices = list("Linear regression"="reg", "PCA (total least squares)"="pca"), 
  selected = "reg",
  width = "100%"
)

p("Covariance matrix (double-click to edit):", style="margin-bottom:-10px")
DTOutput("sigma")
output$sigma <- renderDT(datatable(
  sigma(), options = list(dom = "t", ordering = FALSE),
  rownames = NULL, colnames = c("V1", "V2"), editable = TRUE
))

br()
sliderInput("n", "Number of samples", 10, 100, 50, step=10, width="100%")
sliderInput("alpha", "Initial angle:", -85, 85, -45, step=5, width="100%")
sliderInput("cm", "Initial shift:", -3, 3, 1, step=0.5, width="100%")
sliderInput("loss", "Velocity loss:", 5, 30, 7, step=1, post=" %", width="100%")
sliderInput("inertia", "Inertia:", 10, 400, 40, step=10, width="100%")
numericInput("seed", "Seed:", 42, min=0, width="100%")
```

```{r}
observeEvent(input$sigma_cell_edit, {
  info <- input$sigma_cell_edit
  info$col <- info$col + 1
  sigma(editData(sigma(), info, "sigma"))
})

o <- reactive({
  req(input$n, sigma(), input$type, input$seed, input$alpha, input$loss, input$inertia)
  
  X <- generate_data(input$n, as.matrix(sigma()), input$seed)
  o <- list(data = generate_frames(
    X, c(input$cm, input$alpha), input$type, input$loss/100, input$inertia))
  
  o$xlim <- range(o$data$V1)
  o$ylim <- range(o$data$V2)
  o$slope <- get_slope(X, input$type)
  o$deg <- atan(o$slope) * 180/pi
  
  o$oscil <- unique(o$data[, c("t", "cm", "alpha")])
  o$oscil$intercept <- o$oscil$cm
  if (input$type == "pca")
    o$oscil$intercept <- o$oscil$intercept / cos(o$oscil$alpha * pi/180)
  
  o$alpha <- data.frame(alpha=o$deg, t=c(-10, max(o$data$t) + 10))
  o$cm <- data.frame(cm=0, t=c(-10, max(o$data$t) + 10))
  o$line <- data.frame(
    V1=10 * o$xlim, V2=o$slope * 10 * o$xlim, t=rep(unique(o$data$t), each=2))
  o$shad <- data.frame(alpha=o$deg, t=unique(o$data$t))
  
  cm.idx <- with(o$data, V1 == 0 & V2 == 0)
  o$zero <- subset(o$data, cm.idx, c("xend", "yend", "t"))
  colnames(o$zero) <- c("V1", "V2", "t")
  o$data <- subset(o$data, !cm.idx, c("V1", "V2", "xend", "yend", "d", "t"))
  
  o
})
```

## Main {.tabset}

### JS

```{r}
renderPlotly({
  o <- o()
  
  p1 <- plot_ly(x=~V1, y=~V2, frame=~t) %>%
    add_lines(color=I("lightgray"), data=o$line) %>%
    add_markers(color=I("black"), data=o$data) %>%
    add_segments(xend=~xend, yend=~yend, color=I("black"),
                 alpha=0.2, line=list(width=4)) %>%
    add_lines(x=~xend, y=~yend, color=I("blue")) %>%
    add_markers(data=o$zero, size=1, color=I("white"),
                marker=list(line=list(color=I("black"))))
  
  p2 <- plot_ly(x=~t, y=~alpha) %>%
    add_lines(color=I("lightgray"), data=o$alpha) %>%
    add_lines(color=I("black"), data=o$oscil) %>%
    add_markers(frame=~t, size=1, color=I("white"),
                marker=list(line=list(color=I("black"))))
  
  p3 <- plot_ly(x=~t, y=~cm) %>%
    add_lines(color=I("lightgray"), data=o$cm) %>%
    add_lines(color=I("black"), data=o$oscil) %>%
    add_markers(frame=~t, size=1, color=I("white"),
                marker=list(line=list(color=I("black"))))
  
  s1 <- subplot(p2, p3, nrows=2, shareX=TRUE)
  subplot(p1, s1, margin=0.05) %>%
    config(displayModeBar=FALSE) %>%
    animation_opts(frame=40, redraw=FALSE) %>%
    layout(
      xaxis=list(title="V1", range=o$xlim + 0.5*c(-1, 1)),
      yaxis=list(title="V2", range=o$ylim + 0.5*c(-1, 1)),
      xaxis2=list(title="t", range=c(-1, max(o$data$t) + 1)),
      yaxis2=list(title="center of mass"),
      xaxis3=list(title="t", range=c(-1, max(o$data$t) + 1)),
      yaxis3=list(title="angle"),
      showlegend=FALSE
    )
})
```

### GIF

```{r}
renderImage({
  o <- o()
  outfile <- tempfile(fileext=".gif")
  
  anim <- ggplot(o$data) +
    theme_bw() + theme(legend.position="none") +
    coord_fixed(xlim=o$xlim, ylim=o$ylim) +
    aes(V1, V2) +
    geom_abline(aes(intercept=0, slope=tan(alpha*pi/180)), o$shad, alpha=0.3) +
    geom_segment(aes(xend=xend, yend=yend, alpha=d), color="darkgray", size=2) +
    geom_point() +
    geom_abline(aes(intercept=intercept, slope=tan(alpha*pi/180)), o$oscil, color="blue") +
    geom_point(data=o$zero, size=2, fill="white", shape=21) +
    transition_time(t)

  anim_save(outfile, animate(anim, fps=25, detail=5, renderer=gifski_renderer()))
  
  list(src = outfile, contentType = "image/gif")
}, deleteFile = TRUE)
```
